"""order-cutting-state-and-assignment

Revision ID: 67c42ba49d7b
Revises: b1f2c3d4e5a6
Create Date: 2026-06-17 23:11:37.236150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c42ba49d7b'
down_revision: Union[str, None] = 'b1f2c3d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('assigned_to_label', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###

    # Migrar estado 'approved' eliminado: órdenes y historial pasan a 'in_production'.
    op.execute("UPDATE orders SET status = 'in_production' WHERE status = 'approved'")
    op.execute(
        "UPDATE order_status_history SET to_status = 'in_production' "
        "WHERE to_status = 'approved'"
    )
    op.execute(
        "UPDATE order_status_history SET from_status = 'in_production' "
        "WHERE from_status = 'approved'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'assigned_to_label')
    op.drop_column('orders', 'assigned_at')
    op.drop_column('orders', 'assigned_to_id')
    # ### end Alembic commands ###
