from sqlalchemy import MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from src.shared.config import config

# Deterministic names for every index/constraint (Alembic best practice). Without
# a convention, SQLAlchemy/PostgreSQL assign implicit names that vary between
# environments, making autogenerated migrations non-reproducible. Note: the ``ck``
# template references ``constraint_name``, so every CheckConstraint must be given
# an explicit ``name=`` (the final name becomes ``ck_<table>_<name>``).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ``pool_pre_ping`` validates a pooled connection with a lightweight ping before
# use, discarding ones killed by a Postgres restart or an idle timeout (avoids the
# "server closed the connection unexpectedly" errors after the DB restarts).
# ``pool_recycle`` caps a connection's lifetime so long-lived pools don't hold
# stale sockets. ``pool_size``/``max_overflow`` are configurable per environment.
engine = create_engine(
    config.DATABASE_URL,
    pool_pre_ping=True,
    pool_recycle=config.DB_POOL_RECYCLE_SECONDS,
    pool_size=config.DB_POOL_SIZE,
    max_overflow=config.DB_MAX_OVERFLOW,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    """FastAPI dependency: provides a database session per request."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
